### PR TITLE
security fix

### PR DESCRIPTION
**Pull request by djpiper28**
for https://github.com/TylerBloom/SquireBot/issues/61

### CODE REVIEW

**Comment by djpiper28** [comment]
fixes for https://github.com/TylerBloom/SquireBot/issues/56 and https://github.com/TylerBloom/SquireBot/issues/61

**Comment by TylerBloom** [comment]
I made minor changes to the last commit here and merged to master.

**Comment by djpiper28** [comment]
> I made minor changes to the last commit here and merged to master.

you sure you merged?

**Comment by TylerBloom** [comment]
> > I made minor changes to the last commit here and merged to master.
> 
> you sure you merged?

I just pushed the rebased version. My bad.

**Pull request closed without merging**
